quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=weather
quarkus.datasource.password=weather
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/weather_db


quarkus.hibernate-orm.database.generation=update


openmeteo.geocoding.url=https://geocoding-api.open-meteo.com/v1/search
openmeteo.weather.url=https://api.open-meteo.com/v1/forecast

quarkus.datasource.devservices.enabled=true
quarkus.hibernate-orm.database.generation=drop-and-create